// Seed script to populate the database with questions
// Run with: npx tsx prisma/seed.ts

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import path from 'path';

const dbPath = path.resolve(__dirname, '..', 'dev.db');
console.log('Using database at:', dbPath);

const adapter = new PrismaBetterSqlite3({
    url: dbPath
});
const prisma = new PrismaClient({ adapter });
// Import questions data inline to avoid module resolution issues
const nurseQuestions = [
    // Section 0: Consent and Context
    {
        externalId: 'nurse_consent_participate',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 1,
        text: 'Do you consent to participate in this survey?',
        subText: 'Your responses will help shape the future of nursing technology.',
        type: 'boolean',
        required: true,
    },
    {
        externalId: 'nurse_consent_followup',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 2,
        text: 'Would you be open to a follow-up interview?',
        subText: 'A 15-minute call to discuss your experiences in more detail.',
        type: 'boolean',
        required: false,
    },
    {
        externalId: 'nurse_role',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 3,
        text: 'What is your current role?',
        type: 'choice',
        options: ['Staff Nurse', 'Senior Nurse', 'Nurse In-charge', 'ICU Nurse', 'OT Nurse', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_hospital_type',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 4,
        text: 'What type of hospital do you work in?',
        type: 'choice',
        options: ['Government', 'Private', 'Teaching hospital', 'Clinic'],
        required: true,
    },
    {
        externalId: 'nurse_department',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 5,
        text: 'Which departments do you work in most often?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['OPD', 'Ward', 'ICU', 'Emergency', 'OT', 'Post-op recovery', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_experience',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 6,
        text: 'How many years of experience do you have?',
        type: 'choice',
        options: ['Less than 1 year', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
        required: true,
    },
    {
        externalId: 'nurse_shift_length',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 7,
        text: 'What is your typical shift length?',
        type: 'choice',
        options: ['8 hours', '10 hours', '12 hours', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_patients_per_shift',
        role: 'nurse',
        section: 'Consent and Context',
        sectionOrder: 0,
        order: 8,
        text: 'How many patients do you typically handle per shift?',
        type: 'choice',
        options: ['1-5', '6-10', '11-20', '20+'],
        required: true,
    },
    // Section 1: Daily Workflow
    {
        externalId: 'nurse_time_consuming_tasks',
        role: 'nurse',
        section: 'Daily Workflow',
        sectionOrder: 1,
        order: 1,
        text: 'Which tasks consume most of your time?',
        subText: 'Select your top 5 most time-consuming tasks',
        type: 'multi-choice',
        options: ['Vitals recording', 'Medication administration', 'Documentation', 'Shift handover', 'Calling doctors', 'Patient education', 'Coordination with lab/radiology', 'Billing/insurance coordination', 'Other'],
        config: { maxSelections: 5 },
        required: true,
    },
    {
        externalId: 'nurse_documentation_time',
        role: 'nurse',
        section: 'Daily Workflow',
        sectionOrder: 1,
        order: 2,
        text: 'How much time per shift do you spend on documentation?',
        type: 'choice',
        options: ['Less than 30 min', '30-60 min', '1-2 hours', '2-4 hours', '4+ hours'],
        required: true,
    },
    {
        externalId: 'nurse_documentation_timing',
        role: 'nurse',
        section: 'Daily Workflow',
        sectionOrder: 1,
        order: 3,
        text: 'When do you usually complete documentation?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Real time at bedside', 'After completing tasks', 'At end of shift', 'Mixed'],
        required: true,
    },
    {
        externalId: 'nurse_delay_documentation',
        role: 'nurse',
        section: 'Daily Workflow',
        sectionOrder: 1,
        order: 4,
        text: 'How often do you delay documentation due to workload?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'nurse_documentation_method',
        role: 'nurse',
        section: 'Daily Workflow',
        sectionOrder: 1,
        order: 5,
        text: 'Where do you document today?',
        subText: 'Select all methods you use',
        type: 'multi-choice',
        options: ['Paper forms', 'HIS/EHR system', 'WhatsApp/phone notes then transfer', 'Voice calls to another staff', 'Other'],
        required: true,
    },
    // Section 2: Tools and Friction
    {
        externalId: 'nurse_devices_used',
        role: 'nurse',
        section: 'Tools and Friction',
        sectionOrder: 2,
        order: 1,
        text: 'What devices do you regularly use at work?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Hospital desktop', 'Shared tablet', 'Personal phone', 'Hospital phone', 'None'],
        required: true,
    },
    {
        externalId: 'nurse_system_usability',
        role: 'nurse',
        section: 'Tools and Friction',
        sectionOrder: 2,
        order: 2,
        text: 'How usable is the current hospital system for nurses?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Very poor', high: 'Excellent' } },
        required: true,
    },
    {
        externalId: 'nurse_documentation_challenges',
        role: 'nurse',
        section: 'Tools and Friction',
        sectionOrder: 2,
        order: 3,
        text: 'What makes documentation hard?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Too many fields', 'Slow system', 'Too much typing', 'Frequent interruptions', 'Lack of devices at bedside', 'Login issues', 'Network issues', 'Not nurse-friendly workflow', 'Language issues', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_wishlist_features',
        role: 'nurse',
        section: 'Tools and Friction',
        sectionOrder: 2,
        order: 4,
        text: 'What are the top 3 features you wish your current system had?',
        type: 'textarea',
        config: { placeholder: 'Describe the features that would help you most...' },
        required: false,
    },
    // Section 3: Communication
    {
        externalId: 'nurse_doctor_instruction_method',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 1,
        text: 'How do doctors usually give you instructions?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Verbally during rounds', 'Phone call', 'Written notes', 'EHR orders', 'WhatsApp', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_instruction_clarity',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 2,
        text: 'How often are instructions unclear or incomplete?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'nurse_clarification_frequency',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 3,
        text: 'How often do you need to call back to clarify orders?',
        type: 'choice',
        options: ['Rarely', 'Sometimes', 'Often', 'Daily multiple times'],
        required: true,
    },
    {
        externalId: 'nurse_commonly_missed_orders',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 4,
        text: 'What types of orders are most commonly missed/forgotten due to workload?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Medication timing', 'Lab tests', 'Monitoring frequency', 'Fluid intake/output tracking', 'Physiotherapy/exercises', 'Dressing changes', 'Escalations to doctor', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_order_confirmation',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 5,
        text: 'When an order is completed, how do you confirm it today?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Tick on paper', 'Update EHR', 'Verbally inform doctor', 'WhatsApp', 'Often not confirmed'],
        required: true,
    },
    {
        externalId: 'nurse_task_slip_reason',
        role: 'nurse',
        section: 'Communication',
        sectionOrder: 3,
        order: 6,
        text: 'What is the biggest reason tasks slip?',
        type: 'choice',
        options: ['Too many patients', 'Interruptions', 'Poor handover', 'Missing reminders', 'Unclear instruction', 'Documentation backlog', 'Other'],
        required: true,
    },
    // Section 4: Shift Handover
    {
        externalId: 'nurse_handover_method',
        role: 'nurse',
        section: 'Shift Handover',
        sectionOrder: 4,
        order: 1,
        text: 'How is shift handover done?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Verbal only', 'Written notes', 'Both', 'Tool-based'],
        required: true,
    },
    {
        externalId: 'nurse_handover_duration',
        role: 'nurse',
        section: 'Shift Handover',
        sectionOrder: 4,
        order: 2,
        text: 'How long is handover typically?',
        type: 'choice',
        options: ['Less than 5 min', '5-10 min', '10-20 min', '20+ min'],
        required: true,
    },
    {
        externalId: 'nurse_handover_miss_frequency',
        role: 'nurse',
        section: 'Shift Handover',
        sectionOrder: 4,
        order: 3,
        text: 'How often do important details get missed in handover?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'nurse_handover_missed_items',
        role: 'nurse',
        section: 'Shift Handover',
        sectionOrder: 4,
        order: 4,
        text: 'What gets missed most in handover?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Pending meds', 'Pending labs', 'Recent changes in vitals', 'Doctor instructions', 'Patient complaints', 'High-risk warnings', 'Family instructions'],
        required: true,
    },
    {
        externalId: 'nurse_ai_handover_usefulness',
        role: 'nurse',
        section: 'Shift Handover',
        sectionOrder: 4,
        order: 5,
        text: 'If an AI auto-generated handover summary existed, how useful would it be?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Extremely useful' } },
        required: true,
    },
    // Section 5: Errors and Risk
    {
        externalId: 'nurse_documentation_gap_problems',
        role: 'nurse',
        section: 'Errors and Risk',
        sectionOrder: 5,
        order: 1,
        text: 'How often do documentation gaps cause problems?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'nurse_common_incidents',
        role: 'nurse',
        section: 'Errors and Risk',
        sectionOrder: 5,
        order: 2,
        text: 'What types of incidents are most common?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Missed medication time', 'Wrong medication dose/time', 'Missed escalation', 'Missing documentation for vitals', 'Missed lab follow-up', 'Handover miss', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_near_misses',
        role: 'nurse',
        section: 'Errors and Risk',
        sectionOrder: 5,
        order: 3,
        text: 'In the last 30 days, how many "near misses" did you observe?',
        type: 'choice',
        options: ['0', '1-2', '3-5', '5+'],
        required: true,
    },
    {
        externalId: 'nurse_one_pain_point',
        role: 'nurse',
        section: 'Errors and Risk',
        sectionOrder: 5,
        order: 4,
        text: 'If you could remove ONE pain point instantly, what would it be?',
        type: 'textarea',
        config: { placeholder: 'Describe your biggest challenge...' },
        required: true,
    },
    // Section 6: Voice Capture
    {
        externalId: 'nurse_voice_comfort',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 1,
        text: 'Would you be comfortable speaking short notes aloud at bedside?',
        type: 'choice',
        options: ['Yes', 'No', 'Depends'],
        required: true,
    },
    {
        externalId: 'nurse_voice_conditions',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 2,
        text: 'What conditions would make voice capture acceptable?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Patient consent', 'Private mode', 'Only nurse voice captured', 'No recording stored', 'Works offline', 'Works without headset', 'Other'],
        conditions: [{ questionId: 'nurse_voice_comfort', operator: 'equals', value: 'Depends' }],
        required: true,
    },
    {
        externalId: 'nurse_voice_locations',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 3,
        text: 'Where would voice capture be acceptable?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['ICU', 'Ward', 'Emergency', 'OPD', 'Not acceptable anywhere'],
        conditions: [{ questionId: 'nurse_voice_comfort', operator: 'notEquals', value: 'No' }],
        required: true,
    },
    {
        externalId: 'nurse_voice_concerns',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 4,
        text: 'What is your main concern about voice capture?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Privacy', 'Patient comfort', 'Noise and accuracy', 'Fear of being monitored', 'Extra workload', 'Device availability'],
        required: true,
    },
    {
        externalId: 'nurse_noise_level',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 5,
        text: 'What is the typical noise level in your environment?',
        type: 'choice',
        options: ['Low', 'Medium', 'High', 'Very high'],
        required: true,
    },
    {
        externalId: 'nurse_languages',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 6,
        text: 'What languages do you use in nurse-patient communication?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['English', 'Hindi', 'Malayalam', 'Tamil', 'Mixed (code-switching)', 'Other'],
        required: true,
    },
    {
        externalId: 'nurse_code_switching',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 7,
        text: 'How often do you switch between languages (code-switching)?',
        type: 'choice',
        options: ['Never', 'Sometimes', 'Often', 'Almost always'],
        required: true,
    },
    {
        externalId: 'nurse_acceptable_delay',
        role: 'nurse',
        section: 'Voice Capture',
        sectionOrder: 6,
        order: 8,
        text: 'What delay is acceptable for AI to generate structured notes after speaking?',
        type: 'choice',
        options: ['Real time (0-5 sec)', '10-30 sec', '1-2 min', '5+ min is fine'],
        required: true,
    },
    // Section 7: Smart Forms
    {
        externalId: 'nurse_smart_forms_benefit',
        role: 'nurse',
        section: 'Smart Forms',
        sectionOrder: 7,
        order: 1,
        text: 'Which documentation would benefit most from smart forms?',
        subText: 'Pick up to 3',
        type: 'multi-choice',
        options: ['Vitals', 'Medication administration record', 'Nursing notes', 'Intake/output', 'Wound care', 'Pain scoring', 'Post-op rehab exercises', 'Incident reporting'],
        config: { maxSelections: 3 },
        required: true,
    },
    {
        externalId: 'nurse_auto_followup',
        role: 'nurse',
        section: 'Smart Forms',
        sectionOrder: 7,
        order: 2,
        text: 'Would you like the system to ask follow-up questions automatically?',
        type: 'choice',
        options: ['Yes', 'No', 'Only in some cases'],
        required: true,
    },
    {
        externalId: 'nurse_followup_cases',
        role: 'nurse',
        section: 'Smart Forms',
        sectionOrder: 7,
        order: 3,
        text: 'In which cases should the system prompt follow-up questions?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['High pain score', 'Abnormal vitals', 'Post-op complications', 'Chest pain', 'Low oxygen', 'Confusion/delirium', 'Falls risk'],
        conditions: [{ questionId: 'nurse_auto_followup', operator: 'in', value: ['Yes', 'Only in some cases'] }],
        required: true,
    },
    {
        externalId: 'nurse_completeness_strictness',
        role: 'nurse',
        section: 'Smart Forms',
        sectionOrder: 7,
        order: 4,
        text: 'How strict should the system be in enforcing completeness?',
        type: 'choice',
        options: ['Soft suggestions only', 'Moderate prompts', 'Hard block until filled'],
        required: true,
    },
    // Section 8: Reminders
    {
        externalId: 'nurse_reminders_helpful',
        role: 'nurse',
        section: 'Reminders',
        sectionOrder: 8,
        order: 1,
        text: 'Would timed reminders help you?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not at all', high: 'Extremely helpful' } },
        required: true,
    },
    {
        externalId: 'nurse_reminder_types',
        role: 'nurse',
        section: 'Reminders',
        sectionOrder: 8,
        order: 2,
        text: 'What types of reminders do you need most?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Medication schedule', 'Vitals frequency', 'Lab follow-ups', 'Escalation triggers', 'Exercise/physio steps', 'Dressing changes'],
        required: true,
    },
    {
        externalId: 'nurse_reminder_preference',
        role: 'nurse',
        section: 'Reminders',
        sectionOrder: 8,
        order: 3,
        text: 'How do you prefer to receive reminders?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Phone notification', 'Tablet notification', 'Nurse station display', 'Smartwatch', 'Printed task list'],
        required: true,
    },
    {
        externalId: 'nurse_patient_checklist',
        role: 'nurse',
        section: 'Reminders',
        sectionOrder: 8,
        order: 4,
        text: 'Would a checklist per patient improve your shift?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not at all', high: 'Significantly' } },
        required: true,
    },
    // Section 9: Adoption
    {
        externalId: 'nurse_replacement_preference',
        role: 'nurse',
        section: 'Adoption',
        sectionOrder: 9,
        order: 1,
        text: 'Do you want this tool to replace or assist your current documentation?',
        type: 'choice',
        options: ['Assist initially, later replace', 'Must integrate into existing system', 'Only if it fully replaces'],
        required: true,
    },
    {
        externalId: 'nurse_adoption_blocker',
        role: 'nurse',
        section: 'Adoption',
        sectionOrder: 9,
        order: 2,
        text: 'What is the biggest blocker to adoption?',
        type: 'choice',
        options: ['Management approval', 'IT restrictions', 'Privacy policy', 'Device availability', 'Too hard to use', 'Not accurate enough'],
        required: true,
    },
    {
        externalId: 'nurse_accuracy_requirement',
        role: 'nurse',
        section: 'Adoption',
        sectionOrder: 9,
        order: 3,
        text: 'What accuracy level would make the tool usable?',
        type: 'choice',
        options: ['70% with nurse edit', '85% with nurse edit', '95%+ almost perfect'],
        required: true,
    },
    {
        externalId: 'nurse_time_saved_requirement',
        role: 'nurse',
        section: 'Adoption',
        sectionOrder: 9,
        order: 4,
        text: 'How much time saved per shift would make it worth using?',
        type: 'choice',
        options: ['10 minutes', '30 minutes', '1 hour', '2+ hours'],
        required: true,
    },
    // Section 10: Pilot
    {
        externalId: 'nurse_pilot_willingness',
        role: 'nurse',
        section: 'Pilot',
        sectionOrder: 10,
        order: 1,
        text: 'Would you join a 2-week pilot program?',
        type: 'choice',
        options: ['Yes', 'No', 'Maybe'],
        required: true,
    },
    {
        externalId: 'nurse_pilot_requirements',
        role: 'nurse',
        section: 'Pilot',
        sectionOrder: 10,
        order: 2,
        text: 'What would you require for a pilot?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Training session', 'On-site support', 'Clear consent flow', 'No medico-legal risk on nurse', 'Minimal extra steps'],
        conditions: [{ questionId: 'nurse_pilot_willingness', operator: 'in', value: ['Yes', 'Maybe'] }],
        required: true,
    },
    {
        externalId: 'nurse_followup_time',
        role: 'nurse',
        section: 'Pilot',
        sectionOrder: 10,
        order: 3,
        text: 'Best time for a follow-up interview (15 min)?',
        type: 'choice',
        options: ['Morning', 'Afternoon', 'Night'],
        conditions: [{ questionId: 'nurse_consent_followup', operator: 'equals', value: true }],
        required: false,
    },
    {
        externalId: 'nurse_additional_suggestions',
        role: 'nurse',
        section: 'Pilot',
        sectionOrder: 10,
        order: 4,
        text: 'Any additional suggestions or concerns?',
        type: 'textarea',
        config: { placeholder: 'Share your thoughts, fears, or ideas...' },
        required: false,
    },
];

const doctorQuestions = [
    // Section 0: Consent and Profile
    {
        externalId: 'doctor_consent_participate',
        role: 'doctor',
        section: 'Consent and Profile',
        sectionOrder: 0,
        order: 1,
        text: 'Do you consent to participate in this survey?',
        subText: 'Your insights will help improve nursing technology and patient care.',
        type: 'boolean',
        required: true,
    },
    {
        externalId: 'doctor_specialty',
        role: 'doctor',
        section: 'Consent and Profile',
        sectionOrder: 0,
        order: 2,
        text: 'What is your specialty?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Ortho', 'Neuro', 'Medicine', 'Surgery', 'Emergency', 'ICU', 'Other'],
        required: true,
    },
    {
        externalId: 'doctor_experience',
        role: 'doctor',
        section: 'Consent and Profile',
        sectionOrder: 0,
        order: 3,
        text: 'How many years of experience do you have?',
        type: 'choice',
        options: ['Less than 1 year', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
        required: true,
    },
    {
        externalId: 'doctor_setting',
        role: 'doctor',
        section: 'Consent and Profile',
        sectionOrder: 0,
        order: 4,
        text: 'What is your primary work setting?',
        type: 'choice',
        options: ['OPD', 'Ward rounds', 'ICU', 'Emergency', 'OT', 'Mixed'],
        required: true,
    },
    // Section 1: Orders and Documentation
    {
        externalId: 'doctor_order_method',
        role: 'doctor',
        section: 'Orders and Documentation',
        sectionOrder: 1,
        order: 1,
        text: 'How do you usually issue orders?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['EHR orders', 'Written notes', 'Verbal to nurse', 'WhatsApp/call'],
        required: true,
    },
    {
        externalId: 'doctor_verbal_vs_written',
        role: 'doctor',
        section: 'Orders and Documentation',
        sectionOrder: 1,
        order: 2,
        text: 'What percentage of your orders are verbal vs written?',
        type: 'choice',
        options: ['Mostly written', 'Balanced', 'Mostly verbal'],
        required: true,
    },
    {
        externalId: 'doctor_orders_not_followed',
        role: 'doctor',
        section: 'Orders and Documentation',
        sectionOrder: 1,
        order: 3,
        text: 'How often do you find orders were not followed exactly as intended?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'doctor_order_failure_causes',
        role: 'doctor',
        section: 'Orders and Documentation',
        sectionOrder: 1,
        order: 4,
        text: 'What are the top causes when orders are not followed?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Miscommunication', 'Workload', 'Shift change', 'Documentation gaps', 'Unclear order format', 'Device/system issues'],
        required: true,
    },
    // Section 2: Nurse Communication
    {
        externalId: 'doctor_nurse_clarification_frequency',
        role: 'doctor',
        section: 'Nurse Communication',
        sectionOrder: 2,
        order: 1,
        text: 'How often do nurses call you for clarification?',
        type: 'choice',
        options: ['Rare', 'Weekly', 'Daily', 'Multiple times daily'],
        required: true,
    },
    {
        externalId: 'doctor_common_clarifications',
        role: 'doctor',
        section: 'Nurse Communication',
        sectionOrder: 2,
        order: 2,
        text: 'Which clarifications are most common?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Dosage/timing', 'Lab follow-ups', 'Escalation thresholds', 'Patient complaints', 'Post-op care steps'],
        required: true,
    },
    {
        externalId: 'doctor_structured_notes_value',
        role: 'doctor',
        section: 'Nurse Communication',
        sectionOrder: 2,
        order: 3,
        text: 'Would structured nurse notes improve your decision-making?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not at all', high: 'Significantly' } },
        required: true,
    },
    {
        externalId: 'doctor_valuable_note_content',
        role: 'doctor',
        section: 'Nurse Communication',
        sectionOrder: 2,
        order: 4,
        text: 'What nurse note content is most valuable to you?',
        subText: 'Pick 3',
        type: 'multi-choice',
        options: ['Patient complaints timeline', 'Pain score trends', 'Vitals trends', 'Medication adherence', 'Intake/output', 'Neuro status changes', 'Wound status'],
        config: { maxSelections: 3 },
        required: true,
    },
    // Section 3: Voice Capture
    {
        externalId: 'doctor_voice_nurse_notes',
        role: 'doctor',
        section: 'Voice Capture',
        sectionOrder: 3,
        order: 1,
        text: 'Would you accept a system that converts nurse spoken notes into structured documentation?',
        type: 'choice',
        options: ['Yes', 'No', 'Depends'],
        required: true,
    },
    {
        externalId: 'doctor_voice_conditions',
        role: 'doctor',
        section: 'Voice Capture',
        sectionOrder: 3,
        order: 2,
        text: 'What conditions are needed for you to accept voice-based documentation?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Nurse verifies before saving', 'Only structured text stored, no audio', 'Consent from patient', 'Department-limited pilot', 'Audit trail for edits'],
        conditions: [{ questionId: 'doctor_voice_nurse_notes', operator: 'equals', value: 'Depends' }],
        required: true,
    },
    {
        externalId: 'doctor_capture_during_rounds',
        role: 'doctor',
        section: 'Voice Capture',
        sectionOrder: 3,
        order: 3,
        text: 'Should the system capture doctor speech during rounds?',
        type: 'choice',
        options: ['Yes', 'No', 'Only if doctor confirms before saving'],
        required: true,
    },
    {
        externalId: 'doctor_extract_from_speech',
        role: 'doctor',
        section: 'Voice Capture',
        sectionOrder: 3,
        order: 4,
        text: 'If captured, what should the AI extract from your speech?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Orders into tasks', 'Key diagnoses', 'Follow-ups', 'Medication changes', 'Risk warnings'],
        conditions: [{ questionId: 'doctor_capture_during_rounds', operator: 'notEquals', value: 'No' }],
        required: true,
    },
    {
        externalId: 'doctor_acceptable_latency',
        role: 'doctor',
        section: 'Voice Capture',
        sectionOrder: 3,
        order: 5,
        text: 'What delay is acceptable for structured output?',
        type: 'choice',
        options: ['Real time', '10-30 sec', '1-2 min', '5+ min'],
        required: true,
    },
    // Section 4: Safety and Escalation
    {
        externalId: 'doctor_time_sensitive_escalations',
        role: 'doctor',
        section: 'Safety and Escalation',
        sectionOrder: 4,
        order: 1,
        text: 'What nurse-to-doctor escalations are most time sensitive?',
        subText: 'Pick 3',
        type: 'multi-choice',
        options: ['Low oxygen', 'BP drop', 'Chest pain', 'Altered mental status', 'Post-op bleeding', 'Fever/sepsis signs'],
        config: { maxSelections: 3 },
        required: true,
    },
    {
        externalId: 'doctor_ai_escalation_prompts',
        role: 'doctor',
        section: 'Safety and Escalation',
        sectionOrder: 4,
        order: 2,
        text: 'Would you want AI-suggested escalation prompts based on vitals or notes?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not at all', high: 'Definitely' } },
        required: true,
    },
    {
        externalId: 'doctor_escalation_sensitivity',
        role: 'doctor',
        section: 'Safety and Escalation',
        sectionOrder: 4,
        order: 3,
        text: 'Should escalations be conservative or precise?',
        type: 'choice',
        options: ['Conservative (more alerts)', 'Balanced', 'Precise (fewer alerts)'],
        required: true,
    },
    {
        externalId: 'doctor_acceptable_false_alerts',
        role: 'doctor',
        section: 'Safety and Escalation',
        sectionOrder: 4,
        order: 4,
        text: 'How many false alerts per shift is acceptable?',
        type: 'choice',
        options: ['0-1', '2-5', '5-10', '10+'],
        required: true,
    },
    // Section 5: Handover
    {
        externalId: 'doctor_handover_issues',
        role: 'doctor',
        section: 'Handover',
        sectionOrder: 5,
        order: 1,
        text: 'Do you see issues due to nurse shift handover gaps?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Never', high: 'Very often' } },
        required: true,
    },
    {
        externalId: 'doctor_auto_handover_value',
        role: 'doctor',
        section: 'Handover',
        sectionOrder: 5,
        order: 2,
        text: 'Would auto-generated handover summaries reduce errors?',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not at all', high: 'Significantly' } },
        required: true,
    },
    {
        externalId: 'doctor_handover_must_include',
        role: 'doctor',
        section: 'Handover',
        sectionOrder: 5,
        order: 3,
        text: 'What must be included in a handover summary?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Pending tasks', 'Critical changes', 'Watch-outs', 'Recent orders', 'Family issues', 'Medication schedule exceptions'],
        required: true,
    },
    // Section 6: Compliance
    {
        externalId: 'doctor_current_system',
        role: 'doctor',
        section: 'Compliance',
        sectionOrder: 6,
        order: 1,
        text: 'What documentation system do you currently use?',
        type: 'text',
        config: { placeholder: 'e.g., Epic, Cerner, custom HIS, paper...' },
        required: true,
    },
    {
        externalId: 'doctor_parallel_tool',
        role: 'doctor',
        section: 'Compliance',
        sectionOrder: 6,
        order: 2,
        text: 'Would you allow a parallel documentation tool in pilot stage?',
        type: 'boolean',
        required: true,
    },
    {
        externalId: 'doctor_compliance_requirements',
        role: 'doctor',
        section: 'Compliance',
        sectionOrder: 6,
        order: 3,
        text: 'What are non-negotiable compliance requirements?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Role-based access', 'Audit logs', 'Consent', 'Data encryption', 'On-prem deployment', 'No audio storage'],
        required: true,
    },
    {
        externalId: 'doctor_note_responsibility',
        role: 'doctor',
        section: 'Compliance',
        sectionOrder: 6,
        order: 4,
        text: 'Who should own responsibility for note correctness?',
        type: 'choice',
        options: ['Nurse', 'Doctor', 'Hospital policy', 'Shared with explicit verification step'],
        required: true,
    },
    // Section 7: Feature Priority
    {
        externalId: 'doctor_feature_voice_notes',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 1,
        text: 'Rate: Voice to structured nursing note',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    {
        externalId: 'doctor_feature_task_list',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 2,
        text: 'Rate: Task list from doctor orders',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    {
        externalId: 'doctor_feature_reminders',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 3,
        text: 'Rate: Timed reminders for meds and vitals',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    {
        externalId: 'doctor_feature_handover',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 4,
        text: 'Rate: Auto shift handover summary',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    {
        externalId: 'doctor_feature_timeline',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 5,
        text: 'Rate: Patient timeline summary',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    {
        externalId: 'doctor_feature_escalation',
        role: 'doctor',
        section: 'Feature Priority',
        sectionOrder: 7,
        order: 6,
        text: 'Rate: Escalation recommendations',
        type: 'likert',
        config: { min: 1, max: 5, likertLabels: { low: 'Not useful', high: 'Essential' } },
        required: true,
    },
    // Section 8: Procurement
    {
        externalId: 'doctor_approval_authority',
        role: 'doctor',
        section: 'Procurement',
        sectionOrder: 8,
        order: 1,
        text: 'Who would approve such a tool?',
        subText: 'Select all that apply',
        type: 'multi-choice',
        options: ['Medical superintendent', 'Nursing head', 'IT', 'Department head', 'CEO/management'],
        required: true,
    },
    {
        externalId: 'doctor_pricing_model',
        role: 'doctor',
        section: 'Procurement',
        sectionOrder: 8,
        order: 2,
        text: 'What pricing model fits hospitals?',
        type: 'choice',
        options: ['Per bed per month', 'Per department per month', 'Per hospital license', 'Per active user'],
        required: true,
    },
    {
        externalId: 'doctor_purchase_justification',
        role: 'doctor',
        section: 'Procurement',
        sectionOrder: 8,
        order: 3,
        text: 'What outcome would justify purchase?',
        subText: 'Pick up to 3',
        type: 'multi-choice',
        options: ['Reduced nurse documentation time', 'Reduced medication errors', 'Better compliance', 'Faster response to deterioration', 'Better patient satisfaction'],
        config: { maxSelections: 3 },
        required: true,
    },
    {
        externalId: 'doctor_pilot_willingness',
        role: 'doctor',
        section: 'Procurement',
        sectionOrder: 8,
        order: 4,
        text: 'Would you participate in a 2-4 week pilot?',
        type: 'choice',
        options: ['Yes', 'No', 'Maybe'],
        required: true,
    },
    {
        externalId: 'doctor_additional_concerns',
        role: 'doctor',
        section: 'Procurement',
        sectionOrder: 8,
        order: 5,
        text: 'Any additional requirements or concerns?',
        type: 'textarea',
        config: { placeholder: 'Share your thoughts...' },
        required: false,
    },
];

const allQuestions = [...nurseQuestions, ...doctorQuestions];

async function main() {
    console.log('🌱 Seeding database...');

    // Clear existing questions
    await prisma.question.deleteMany();
    console.log('✓ Cleared existing questions');

    // Insert all questions
    for (const q of allQuestions) {
        await prisma.question.create({
            data: {
                externalId: q.externalId,
                role: q.role,
                section: q.section,
                sectionOrder: q.sectionOrder,
                order: q.order,
                text: q.text,
                subText: q.subText || null,
                type: q.type,
                options: q.options ? JSON.stringify(q.options) : null,
                required: q.required ?? true,
                isActive: true,
                conditions: q.conditions ? JSON.stringify(q.conditions) : null,
                config: q.config ? JSON.stringify(q.config) : null,
            }
        });
    }

    console.log(`✓ Inserted ${allQuestions.length} questions`);
    console.log(`  - ${nurseQuestions.length} nurse questions`);
    console.log(`  - ${doctorQuestions.length} doctor questions`);
    console.log('✅ Seeding complete!');
}

main()
    .catch((e) => {
        console.error('❌ Seeding failed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
